services:
  phoenix:
    build: .
    container_name: blog_phoenix
    depends_on:
      postgres:
        condition: service_healthy
    ports:
      - "4000:4000"
    volumes:
      - ".:/app:Z"
    env_file:
      - ./.env
    restart: unless-stopped

  postgres:
    image: postgres:18
    container_name: blog_postgres
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
      POSTGRES_INITDB_ARGS: "--locale-provider=icu --icu-locale=pt-BR --text-search-config=portuguese"
      TZ: America/Sao_Paulo
    volumes:
      - postgres_data:/var/lib/postgresql
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${DB_USER}"]
      interval: 1s
      timeout: 2s
      retries: 10

volumes:
  postgres_data:
