#!/bin/sh
set -e

if docker compose ps --services --status running | grep -q "^phoenix$"; then
	CONTAINER_ON=1
else
	CONTAINER_ON=0
fi

cleanup() {
	if [ "$CONTAINER_ON" -eq 0]; then
		docker compose down > /dev/null
	fi
}

trap cleanup EXIT

docker compose up -d --wait

docker exec -i blog_phoenix mix precommit
